sudo: true
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master

env:
   
before_install:
  - apt-get install -y freeglut3-dev libglu1-mesa
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - git clone https://github.com/yxqd/dotmantid ~/.mantid

install:
  - echo install
  
script:
  - echo run test
  - ls /usr/lib/libGL*

notifications:
  email:
    on_success: change
    on_failure: always
